import os, re

# Complete Chinese → English translation dictionary
TRANSLATIONS = {
    # Bhop
    "連跳": "Bunny Hop",
    "連跳僅按鍵": "Bhop Keybind Only",
    "連跳自動跑": "Bhop Auto Run",
    "連跳蹲下": "Bhop Crouch",
    "連跳跳蟲": "Bhop Jumpbug",
    "連跳邊緣蟲": "Bhop Edgebug",
    "連跳模式": "Bhop Mode",
    "連跳延遲": "Bhop Delay",
    "連跳速度": "Bhop Speed",
    "連跳音效": "Bhop Sound",
    "連跳延遲適應": "Bhop Delay Adapt",
    "連跳偵測": "Bhop Detection",
    "連跳綁定(空白鍵)": "Bhop Bind (Space)",
    "連跳自動旋轉按鍵": "Bhop Auto Strafe Key",
    "自動旋轉": "Auto Strafe",
    "旋轉模式": "Strafe Mode",
    "旋轉速度": "Strafe Speed",
    "旋轉角度限制": "Strafe Angle Limit",
    "旋轉靈敏度": "Strafe Sensitivity",
    "前衝旋轉": "Forward Strafe",
    "空中加速": "Air Acceleration",
    "地面旋轉": "Ground Strafe",
    "預旋轉": "Pre-Strafe",
    "多段跳": "Multi Jump",
    "體力系統": "Stamina System",
    "速度指示器": "Speed Indicator",
    "體力跳": "Stamina Jump",

    # Aimbot / Combat
    "自瞄": "Aimbot",
    "自瞄視野": "Aimbot FOV",
    "自瞄視野圈": "Aimbot FOV Circle",
    "自瞄平滑": "Aimbot Smoothing",
    "自瞄最小平滑": "Aimbot Min Smooth",
    "自瞄延遲補償": "Aimbot Lag Comp",
    "自瞄延遲適應": "Aimbot Lag Adapt",
    "自瞄距離縮放": "Aimbot Dist Scale",
    "自瞄預測": "Aimbot Prediction",
    "自瞄預測因子": "Aimbot Pred Factor",
    "自瞄自動開鏡": "Aimbot Auto Scope",
    "自瞄自動急停": "Aimbot Auto Stop",
    "自瞄鎖定": "Aimbot Lock",
    "自瞄按鍵": "Aimbot Key",
    "自瞄按鍵綁定": "Aimbot Keybind",
    "自瞄目標切換": "Aimbot Target Switch",
    "自瞄目標資訊": "Aimbot Target Info",
    "自瞄骨骼": "Aimbot Bone",
    "自瞄排序": "Aimbot Sort",
    "自瞄隊友檢查": "Aimbot Team Check",
    "自瞄好友檢查": "Aimbot Friend Check",
    "自瞄可視檢查": "Aimbot Visibility Check",
    "自瞄偵測": "Aimbot Detection",
    "自瞄甩槍": "Aimbot Flick",
    "自瞄抖動": "Aimbot Jitter",
    "自動預測": "Auto Prediction",
    "自動平滑": "Auto Smooth",
    "自動開火": "Auto Fire",
    "自動手槍": "Auto Pistol",
    "自動衝刺": "Auto Sprint",
    "自動評分": "Auto Rate",
    "自動購買": "Auto Buy",
    "自動舉報": "Auto Report",
    "自動斷線": "Auto Disconnect",
    "優先爆頭": "Prioritize Headshot",
    "靜瞄穿牆檢查": "Silent Aim Wall Check",
    "靜瞄爆頭": "Silent Aim Headshot",
    "靜默瞄準偵測": "Silent Aim Detection",
    "靜瞄": "Silent Aim",
    "反瞄準": "Anti-Aim",
    "反瞄平滑": "Anti-Aim Smooth",
    "正常反瞄": "Normal Anti-Aim",
    "反瞄穿牆檢查": "Anti-Aim Wall Check",
    "反瞄延遲適應": "Anti-Aim Lag Adapt",
    "暴力瞄準": "Rage Aim",
    "Rage 部位": "Rage Hitbox",
    "後座控制": "Recoil Control",
    "後座控制連射": "RCS Rapid Fire",
    "無後座力": "No Recoil",
    "無後座偵測": "No Recoil Detection",
    "反震動": "Anti-Shake",
    "命中修正": "Hit Correction",
    "命中框擴大": "Hitbox Expand",
    "頭部命中框": "Head Hitbox",
    "頭部圓點": "Head Dot",
    "頭部": "Head",
    "部位": "Hitbox",
    "觸發器": "Triggerbot",
    "觸發器偵測": "Triggerbot Detection",
    "觸發器僅按鍵": "Triggerbot Keybind Only",
    "觸發器僅爆頭": "Triggerbot Headshot Only",
    "觸發器穿牆檢查": "Triggerbot Wall Check",
    "觸發器視野檢查": "Triggerbot FOV Check",
    "觸發器隊友檢查": "Triggerbot Team Check",
    "觸發器延遲適應": "Triggerbot Lag Adapt",
    "觸發器連射模式": "Triggerbot Rapid Fire Mode",
    "FL 觸發器": "FL Triggerbot",
    "每把武器設定": "Per Weapon Settings",
    "啟用回溯": "Enable Backtrack",
    "瞬瞄偵測": "Flick Detection",
    "旋轉瞄偵測": "Spin Aim Detection",
    "甩槍偵測": "Flick Shot Detection",
    "命中率": "Hit Rate",
    "命中率顯示": "Hit Rate Display",
    "命中率過濾": "Hit Rate Filter",
    "命中率過濾": "Hit Rate Filter",

    # ESP
    "透視": "ESP",
    "穿牆": "Wallhack",
    "穿牆顯示": "Wallhack Display",
    "穿牆偵測": "Wallhack Detection",
    "穿牆伤害衰减": "Wallhack Damage Falloff",
    "穿牆透明度": "Wallhack Opacity",
    "透視穿牆": "ESP Wallhack",
    "透視品質縮放": "ESP Quality Scale",
    "透視顏色模式": "ESP Color Mode",
    "透視偵測": "ESP Detection",
    "透視延遲適應": "ESP Lag Adapt",
    "距離透視": "Distance ESP",
    "名字透視": "Name ESP",
    "名字背景": "Name Background",
    "名字字體大小": "Name Font Size",
    "名字對齊": "Name Alignment",
    "血量條": "Health Bar",
    "血量顏色": "Health Color",
    "血量十字": "Health Cross",
    "護甲條": "Armor Bar",
    "血量": "Health",
    "方框線寬": "Box Thickness",
    "顯示玩家": "Show Players",
    "顯示玩家標籤": "Show Player Tags",
    "顯示FPS": "Show FPS",
    "顯示爆頭率": "Show HS Rate",
    "顯示擊殺/死亡": "Show Kill/Death",
    "顯示延遲統計": "Show Ping Stats",
    "顯示時間": "Show Time",
    "顯示場次統計": "Show Session Stats",
    "顯示觀戰模式": "Show Spectate Mode",
    "FPS 顯示": "FPS Display",
    "武器透視": "Weapon ESP",
    "武器彈藥": "Weapon Ammo",
    "掉落武器透視": "Dropped Weapon ESP",
    "手榴彈透視": "Grenade ESP",
    "手榴彈線": "Grenade Line",
    "手榴彈預覽": "Grenade Preview",
    "炸彈透視": "Bomb ESP",
    "炸彈距離": "Bomb Distance",
    "炸彈通知": "Bomb Notification",
    "炸彈計時器": "Bomb Timer",
    "拆彈包透視": "Defuse Kit ESP",
    "槍管透視": "Barrel ESP",
    "發光透視": "Glow ESP",
    "容器透視": "Container ESP",
    "載具透視": "Vehicle ESP",
    "物品透視": "Item ESP",
    "材質透視": "Material ESP",
    "刷新材質透視": "Refresh Material ESP",
    "3D聲音透視": "3D Sound ESP",
    "瞄準線": "Aimline",
    "爆頭線": "Headshot Line",
    "距離": "Distance",
    "最大透視距離": "Max ESP Distance",
    "視野值": "FOV Value",
    "視野修改器": "FOV Modifier",
    "視野圈": "FOV Circle",
    "視野衝擊": "FOV Punch",
    "頭部": "Head",

    # Kill Effects / HUD
    "命中標記": "Hitmarker",
    "命中標記大小": "Hitmarker Size",
    "命中標記持續時間": "Hitmarker Duration",
    "自動十字準星": "Auto Crosshair",
    "十字準星大小": "Crosshair Size",
    "十字準星間距": "Crosshair Gap",
    "十字準星輪廓大小": "Crosshair Outline Size",
    "傷害數字": "Damage Numbers",
    "擊殺音效": "Kill Sound",
    "命中音效": "Hit Sound",
    "命中音效風格": "Hit Sound Style",
    "隨機俯仰": "Random Pitch",
    "畫面閃光": "Screen Flash",
    "白色閃光": "White Flash",
    "紅色閃光": "Red Flash",
    "模糊閃光": "Blur Flash",
    "色彩校正": "Color Correction",
    "泛光閃光": "Bloom Flash",
    "太陽光線閃光": "Sun Rays Flash",
    "畫面震動": "Screen Shake",
    "色差效果": "Chromatic Aberration",
    "暗角 (紅邊)": "Vignette (Red Edge)",
    "血液粒子": "Blood Particles",
    "擊殺擴散圈": "Kill Ring",
    "去飽和度 (CS2)": "Desaturate (CS2)",
    "故障線條": "Glitch Lines",
    "慢動作視野": "Slow Motion FOV",
    "傷害方向": "Damage Direction",
    "連殺音效": "Kill Streak Sound",
    "連殺文字": "Kill Streak Text",
    "連殺通知": "Kill Streak Notification",
    "連殺顯示": "Kill Streak Display",
    "擊殺訊息覆蓋": "Kill Feed Override",
    "擊殺通知": "Kill Notification",
    "擊殺特效": "Kill Effects",
    "擊殺計數": "Kill Count",
    "擊殺風格": "Kill Style",
    "擊殺文字": "Kill Text",
    "擊殺訊息": "Kill Message",
    "擊殺/死亡 顯示": "Kill/Death Display",
    "爆頭文字": "Headshot Text",
    "爆頭圖標": "Headshot Icon",
    "爆頭線": "Headshot Line",
    "受傷指示器": "Damage Indicator",
    "腳步指示器": "Footstep Indicator",
    "HUD 顯示": "HUD Display",
    "HUD 大小": "HUD Size",
    "HUD 位置": "HUD Position",
    "速度顯示": "Speed Display",
    "延遲顯示": "Ping Display",
    "回合資訊": "Round Info",
    "資訊卡片": "Info Card",
    "玩家數量": "Player Count",
    "玩家數顯示": "Player Count Display",

    # Misc / Utility
    "雜項": "Misc",
    "世界": "World",
    "安全": "Safety",
    "伺服器": "Server",
    "手榴彈": "Grenade",
    "炸彈": "Bomb",
    "恐慌鍵 (INSERT)": "Panic Key (INSERT)",
    "自動重連": "Auto Reconnect",
    "第三人稱": "Third Person",
    "第三人稱碰撞檢查": "Third Person Collision Check",
    "去除煙霧": "Remove Smoke",
    "去除火焰": "Remove Fire",
    "移除霧氣": "Remove Fog",
    "移除血液": "Remove Blood",
    "全亮": "Full Bright",
    "反閃光": "Anti Flash",
    "移動延遲適應": "Movement Lag Adapt",
    "無摔落傷害": "No Fall Damage",
    "無摔落": "No Fall",
    "快速切換": "Quick Switch",
    "射擊後切刀": "Post-Shot Knife",
    "滾輪縮放": "Scroll Zoom",
    "對特定玩家隱藏": "Hide From Specific Player",
    "功能切換通知": "Feature Toggle Notification",
    "功能狀態": "Feature Status",
    "通知中心": "Notification Center",
    "觀戰列表": "Spectator List",
    "觀戰提醒": "Spectator Alert",
    "警告系統": "Warning System",
    "隱藏錯誤": "Hide Errors",
    "加速限制": "Acceleration Limit",
    "角速度限制": "Angular Velocity Limit",
    "速度加成": "Speed Bonus",
    "偽裝": "Spoofing",
    "假延遲": "Fake Lag",
    "延遲偽造": "Lag Spoof",
    "延遲適應": "Lag Adaptation",
    "偽造來源": "Spoof Origin",
    "延遲顯示": "Ping Display",
    "聊天助手": "Chat Assistant",
    "聊天風格": "Chat Style",
    "聊天延遲": "Chat Delay",
    "發送自定義訊息": "Send Custom Message",
    "刷屏繞過": "Spam Bypass",
    "封包數": "Packet Count",
    "啟用SSVL": "Enable SSVL",
    "大廳摘要": "Lobby Summary",
    "錄製精彩片段": "Record Highlights",
    "匯出 (剪貼簿)": "Export (Clipboard)",
    "地圖記憶": "Map Memory",
    "生成硬體 ID": "Generate Hardware ID",
    "比賽開始掃描": "Round Start Scan",
    "掃描間隔": "Scan Interval",

    # Buy
    "購買護甲": "Buy Armor",
    "購買拆彈包": "Buy Defuse Kit",
    "購買手榴彈": "Buy Grenade",
    "自動放彈": "Auto Plant",
    "自動拆彈": "Auto Defuse",
    "拆彈距離": "Defuse Range",
    "炸彈時間": "Bomb Duration",

    # Settings
    "載入設定": "Load Settings",
    "儲存設定": "Save Settings",
    "重置統計": "Reset Stats",
    "全部重置": "Reset All",
    "重置所有評分": "Reset All Ratings",
    "設定 URL": "Set URL",
    "載入正常模式": "Load Normal Mode",
    "載入半暴力模式": "Load Semi-Rage Mode",
    "載入 HvH 模式": "Load HvH Mode",
    "載入暴力模式": "Load Rage Mode",
    "載入通知": "Load Notification",

    # Position/Direction
    "左": "Left",
    "右": "Right",
    "上": "Up",
    "下": "Down",
    "左上": "Top Left",
    "右上": "Top Right",
    "左下": "Bottom Left",
    "右下": "Bottom Right",
    "中上": "Top Center",
    "中下": "Bottom Center",
    "最右": "Far Right",
    "居中": "Center",

    # Misc direction/mode names
    "線性": "Linear",
    "正弦波": "Sine Wave",
    "隨機": "Random",
    "隨机": "Random",
    "進攻": "Aggressive",
    "平滑": "Smooth",
    "圓形": "Circle",
    "正常": "Normal",
    "智能": "Smart",
    "自動": "Auto",
    "自適應": "Adaptive",
    "極致": "Extreme",
    "保守": "Conservative",
    "近距離": "Close Range",
    "暴力": "Rage",
    "雙發": "Double Shot",
    "友善": "Friendly",
    "威脅": "Threat",
    "威胁": "Threat",
    "毒舌": "Toxic",
    "淡入": "Fade In",
    "解析自動": "Parse Auto",

    # Stats/Kill info
    "玩家評分": "Player Rating",
    "風險等級顯示": "Risk Level Display",
    "查看玩家統計": "View Player Stats",
    "威脅閾值": "Threat Threshold",
    "威脅": "Threat",
    "威胁评估": "Threat Assessment",
    "敌人行为分析": "Enemy Behavior Analysis",
    "自适应玩法": "Adaptive Gameplay",
    "武器匹配优化": "Weapon Match Optimization",
    "模式轮换": "Mode Rotation",
    "AI 预测": "AI Prediction",
    "strafe 预测": "Strafe Prediction",
    "跳跃预测": "Jump Prediction",
    "预测精度": "Prediction Accuracy",
    "击杀上限/h": "Kill Cap/h",
    "自我限制": "Self Limit",

    # Visuals misc
    "亮度": "Brightness",
    "對比度": "Contrast",
    "飽和度": "Saturation",
    "去飽和度": "Desaturate",
    "全亮": "Full Bright",
    "顯示爆頭率": "Show HS Rate",
    "放大": "Zoom In",
    "轉換偵測": "Teleport Detection",
    "傳送偵測": "Teleport Detection",

    # Extra
    "軌跡點數": "Trail Points",
    "震動": "Vibration",
    "震撼音效": "Shockwave Sound",
    "解析器": "Parser",
    "角色搖晃(走路)": "Character Sway (Walk)",
    "角色晃動(滑鼠)": "Character Sway (Mouse)",
    "角色後座動畫": "Character Recoil Anim",
    "角色呼吸": "Character Breathing",
    "角色位置": "Character Position",
    "身體旋轉": "Body Rotation",
    "閃光": "Flash",
    "爆炸": "Explosion",
    "破片": "Shrapnel",
    "Quake 命中": "Quake Hit",
    "CS2 命中": "CS2 Hit",
    "Fortnite 風格": "Fortnite Style",
    "MW2 風格": "MW2 Style",
    "Minecraft 經驗": "Minecraft XP",
    "瑪利歐金幣": "Mario Coin",

    # Kill streak descriptions
    "2x Double | 3x Triple | 4x Quad | 5x Penta": "2x Double | 3x Triple | 4x Quad | 5x Penta",
    "7x Unstoppable | 10x Rampage | 15x GODLIKE": "7x Unstoppable | 10x Rampage | 15x GODLIKE",
    "CS2-Style kill feed (top right)": "CS2-Style kill feed (top right)",

    # Stealth
    "隱藏錯誤": "Hide Errors",
    "偽裝鉤子": "Spoof Hooks",
    "備份原始鉤子": "Backup Original Hooks",
    "偵測鉤子掃描": "Detect Hook Scan",
    "保護 Namecall": "Protect Namecall",
    "保護 Index": "Protect Index",
    "混淆字串": "Obfuscate Strings",
    "多態按鍵": "Polymorphic Keys",
    "隱藏GUI名字": "Hide GUI Name",
    "隨機化GUI": "Randomize GUI",
    "加密設定": "Encrypt Settings",
    "隨機化時序": "Randomize Timing",
    "抖動執行": "Jitter Execution",
    "反模式": "Anti Pattern",
    "混淆遠端": "Obfuscate Remotes",
    "限速呼叫": "Rate Limit Calls",
    "封包分散": "Packet Spread",
    "偽造所有屬性": "Spoof All Properties",
    "偽造行走速度": "Spoof Walk Speed",
    "偽造跳躍力": "Spoof Jump Power",
    "偽造臀部高度": "Spoof Hip Height",
    "偽造視野": "Spoof FOV",
    "偽造CFrame": "Spoof CFrame",
    "自動偵測反作弊": "Auto Detect Anti-Cheat",
    "深度掃描": "Deep Scan",
    "監控心跳": "Monitor Heartbeat",
    "偵測遠端鉤子": "Detect Remote Hooks",
    "偵測屬性監控": "Detect Property Monitor",
    "偵測時警告": "Alert On Detection",
    "風險時自動停用": "Auto Disable On Risk",
    "全部人性化": "Humanize All",
    "隨機點擊時序": "Random Click Timing",
    "移動隨機化": "Randomize Movement",
    "瞄準平滑": "Aim Smooth",
    "反應時間": "Reaction Time",
    "機器學習規避": "ML Evasion",
    "移動熵": "Movement Entropy",
    "滑鼠熵": "Mouse Entropy",
    "反應模擬": "Reaction Simulation",
    "決策延遲": "Decision Delay",
    "微暫停": "Micro Pause",
    "統計平滑": "Stat Smoothing",
    "KD 調節": "KD Regulation",
    "爆頭率調節": "HS Rate Regulation",
    "傷害擴散": "Damage Spread",
    "擊殺時序分散": "Kill Timing Spread",
    "武器旋轉": "Weapon Rotation",
    "死亡暫存": "Death Buffer",
    "流量偽裝": "Traffic Masking",
    "噪音注入": "Noise Injection",
    "連射平滑": "Burst Smooth",
    "遠端指紋": "Remote Fingerprint",
    "指紋輪替": "Fingerprint Rotation",
    "名字指紋": "Name Fingerprint",
    "移動指紋": "Move Fingerprint",
    "瞄準指紋": "Aim Fingerprint",
    "時序指紋": "Timing Fingerprint",
    "攝影機指紋": "Camera Fingerprint",
    "停用調試庫": "Disable Debug Library",
    "巨集偵測": "Macro Detection",
    "可視檢查": "Visibility Check",
    "偽造所有屬性": "Spoof All Props",
    "偽造所有屬性": "Spoof All Props",
    "發光隊伍檢查": "Glow Team Check",
    "隊伍檢查": "Team Check",

    # Tab names
    "雜項": "Misc",
    "設定": "Settings",
    "透視": "ESP",
    "自瞄": "Aimbot",
    "世界": "World",
    "隱藏": "Stealth",
    "旁門": "Extra",
    "中文": "English",
    "語言": "Language",
    "額外": "Extra",

    # Misc labels
    "去除瞄準鏡晃動": "Remove Scope Sway",
    "去除瞄準鏡晃動2": "Remove Scope Sway 2",
    "去除瞄準鏡模糊": "Remove Scope Blur",
    "去除瞄準鏡覆蓋": "Remove Scope Overlay",
    "Minecraft 連跳": "Minecraft Hop",
    "加速限制": "Accel Limit",
    "角速度限制": "Angular Vel Limit",
    "手榴彈力度": "Grenade Force",
    "普通": "Normal",

    # Safety
    "啟用 Webhook": "Enable Webhook",
    "擊殺通知": "Kill Notification",
    "死亡通知": "Death Notification",
    "回合通知": "Round Notification",
    "恐慌延遲值": "Panic Delay Value",

    # combatassist / smartai
    "玩家評分": "Player Rating",
    "威胁评估": "Threat Assessment",
    "敌人行为分析": "Enemy Behavior Analysis",
    "自适应玩法": "Adaptive Gameplay",
    "武器匹配优化": "Weapon Optimization",
    "预测精度": "Prediction Accuracy",
    "跳跃预测": "Jump Prediction",
    "strafe 预测": "Strafe Prediction",
    "AI 预测": "AI Prediction",
    "模式轮换": "Mode Rotation",
    "随机": "Random",
    "击杀上限/h": "Kill Cap/h",
}

dir_path = r'C:\Users\pc\Videos\Radeon ReLive\TheOutlaw\YagmurStrike'
zh_pattern = re.compile(r'[\u4e00-\u9fff]')

# Sort by length desc to prevent partial replacements
sorted_translations = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)

replaced_total = 0
for root, dirs, files in os.walk(dir_path):
    # Skip .git
    dirs[:] = [d for d in dirs if d != '.git']
    for file in files:
        if not file.endswith('.lua'):
            continue
        file_path = os.path.join(root, file)
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        original = content
        for zh, en in sorted_translations:
            if zh in content:
                content = content.replace(f'"{zh}"', f'"{en}"')
                content = content.replace(f"'{zh}'", f"'{en}'")
        
        if content != original:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            replaced_total += 1
            print(f"Updated: {file}")

print(f"\nDone! Updated {replaced_total} files.")
